{
    Species: ["p"],
    Reservoirs: {
        Atmosphere: {
            InitMasses: {p: 3.7e9},
            },
        Oceans: {
            InitMasses: {p: 1.55e13},
            },
        OCrust: {
            InitMasses: {p: 5.4e18},
            },
        UMantle: {
        InitMasses: {p: 2.12e20},
        },
        LMantle: {
        InitMasses: {p: 5.90e20},
        },
        CCrust: {
            InitMasses: {
            p: 2.0e19},
            }
            },
   
   Processes:
    ["Erosion","WindErosion","Subduction","Volcanism", "Precipitation","Rainout","CometDelivery","Convection","HydrothermalCirculation",],
   
   Erosion: {uniform_growth: false,
   alpha: 5e-4, #m/yr, riverine erosion rate
   max_conc: 2.2e-6,
   VOcean: 1.35e21,}, #not relevant
    
    WindErosion: {uniform_growth: false, 
    beta: 5e-6, #m/yr wind erosion rate
    satur: 5.57e9,}, #kg, saturation value of the atmosphere (not well constrained)

   Precipitation: {max_conc: 2.2e-6, #Molar (mol of P/liter), Mass concentration of the ocean (to be varied)
   VOcean: 1.35e21, #Liter, totel volume of the oceans
   flux: 0,}, #1.05e10,},

   Rainout: {satur: 5.57e9, #kg
   VAtmos: 4.2e18, #m続, not relevant
   flux: 3.19e8, #kg/yr, constant rainout flux (constrained?)
   uniform_growth: false,}, #not relevant
   
   UVLight: {
        F0: 1.2e-6,
    },
   
   Henry: {
        H0: 6.1e-6,
        V0: 1.3e18,
        change: 0,
        evolution: true
    },
   
   BioticContribution: {
        efficiency: true,
        dbio: 1e8,
        onset: 1e9,
        EA: 0,
        ED: 0,
        const_E6: true,
        E6i: 0.1,
        MMAX: 1e15
    },
   
   Impacts: {
        M_REF: 4e18,
        tau: 0.15e9,
        F0: 4.7e6,
        F1: 4.7e9,
    },
   
   AbioticFixation: {
        M_REF: 4e18,
        Fi_NOx: 4.0e10,
        Fi_NH3: 1.6e7,
        Ff_NOx: 2.6e6,
        Ff_NH3: 1.0e3,
        tau: 0.1e9,
        goe: 100e9
    },
   
   CometDelivery: {
        tau: 0.15e9, #yr
        F0: 1.02e7, #present-day flux, kg/yr value (well constrained)
        F1: 1.02e10, # LHB rate, kg/yr (x1000 larger than F0, ???)
    },
   
   FreundlichAdsorption: {
        VSed: 6.1e17,
        rhoSed: 1700,
        Kf: 1e-3
    },
   
   HydrothermalCirculation: {
        tau: 150e6, # Exp decay constant, yr
        F0: 1e-7,   # Evolution of fraction of circulated ocean water, present-day
        F1: 3e-7,   # Evolution of fraction of circulated ocean water, Early earth (from Laneuville et al)
        F_p: 0.5,   # Fraction of circulated P that gets circulated 
    },
   
   Convection: {
        tau: 1e9,  # Exp decay constant, yr
        F0: 1e-8,  # Evolution of fraction of circulated mantle (from Laneuville et al)
        F1: 3e-8,  # Evolution of fraction of circulated mantle (from Laneuville et al)
    },
   
   Subduction: {
        accretion: 0.05, #fraction of accreted material, constant over time?
        tau: 100e6,  #timescale of total surface recycling
        VCrust: 7.58e18 #unused
    },
   
   Volcanism: {
        F_arc: 0.5, #km続/yr, constant over time?
        F_MORB: 20, #km続/yr, constant over time?
        F_hotspot: 2, #km続/yr, constant over time? 
        density: 2800,
        scaling: 1e21
    },

    Accretion: {
        F0: 
    },
   
    atm_ox: 0.2,
    man_ox: 0.2,
    OutFolder: "output",
    Tmax: 4500e6,
    Output: 10e6,
    Timestep: 5e3,
    Debug: False
}
