{AbioticFixation: {Ff_NH3: 1.0e3, Ff_NOx: 2.6e6, Fi_NH3: 1.6e7, Fi_NOx: 4.0e10, M_REF: 4e18,
    goe: 100e9, tau: 0.1e9}, Accretion: {F0: null}, BioticContribution: {E6i: 0.1,
    EA: 0, ED: 0, MMAX: 1e15, const_E6: true, dbio: 1e8, efficiency: true, onset: 1e9},
  CometDelivery: {F0: 1.02e7, F1: 1.02e10, tau: 0.15e9}, Convection: {F0: 1e-8, F1: 3e-8,
    tau: 1e9}, Debug: false, Erosion: {VOcean: 1.35e21, alpha: 5e-4, max_conc: 2.2e-06,
    uniform_growth: false}, FreundlichAdsorption: {Kf: 1e-3, VSed: 6.1e17, rhoSed: 1700},
  Henry: {H0: 6.1e-06, V0: 1.3e18, change: 0, evolution: true}, HydrothermalCirculation: {
    F0: 1e-7, F1: 3e-7, F_p: 0.5, tau: 150e6}, Impacts: {F0: 4.7e6, F1: 4.7e9, M_REF: 4e18,
    tau: 0.15e9}, OutFolder: output, Output: 10e6, Precipitation: {VOcean: 1.35e21,
    flux: 0, max_conc: 2.2e-06}, Processes: [Erosion, WindErosion, Subduction, Volcanism,
    Precipitation, Rainout, CometDelivery, Convection, HydrothermalCirculation], Rainout: {
    VAtmos: 4.2e18, flux: 3.19e8, satur: 5.57e9, uniform_growth: false}, Reservoirs: {
    Atmosphere: {InitMasses: {p: '7.93e+09'}}, CCrust: {InitMasses: {p: '2.82e+16'}},
    LMantle: {InitMasses: {p: '2.42e+21'}}, OCrust: {InitMasses: {p: '4.54e+11'}},
    Oceans: {InitMasses: {p: '2.28e+14'}}, UMantle: {InitMasses: {p: '1.36e+19'}}},
  Species: [p], Subduction: {VCrust: 7.58e18, accretion: 0.05, tau: 100e6}, Timestep: 5e3,
  Tmax: 4500e6, UVLight: {F0: 1.2e-06}, Volcanism: {F_MORB: 20, F_arc: 5, F_hotspot: 2.5,
    Factor: 3, density: 2800, scaling: 1e21, tau: 150e6}, WindErosion: {beta: 5e-6,
    satur: 5.57e9, uniform_growth: false}, atm_ox: 0.2, man_ox: 0.2}
