{
    Species: ["p"],
    Reservoirs: {
        Atmosphere: {
            InitMasses: {p: 3.7e9},
            },
        Oceans: {
            InitMasses: {p: 9.30e13},
            },
        OCrust: {
            InitMasses: {p: 5.4e18},
            },
        UMantle: {
        InitMasses: {p: 2.12e20},
        },
        LMantle: {
        InitMasses: {p: 5.90e20},
        },
        CCrust: {
            InitMasses: {
            p: 2.0e19},
            }
            },
   
   Processes:
    ["Erosion","WindErosion","Subduction","Volcanism","Precipitation","Rainout","CometDelivery","Convection","HydrothermalCirculation",],
   
   Erosion: {uniform_growth: false,
   alpha: 5e-4,
   max_conc: 4.19e14,},
    
    WindErosion: {uniform_growth: false, 
    beta: 5e-6,
    satur: 1e9,},

   Precipitation: {max_conc: 9.3e13, #4.19e14,
   VOcean: 1.3e18,
   flux: 0,}, #1.05e10,},

   Rainout: {satur: 1e9,
   VAtmos: 4.2e18,
   flux: 3.19e8,
   uniform_growth: false,},
   
   UVLight: {
        F0: 1.2e-6,
    },
   
   Henry: {
        H0: 6.1e-6,
        V0: 1.3e18,
        change: 0,
        evolution: true
    },
   
   BioticContribution: {
        efficiency: true,
        dbio: 1e8,
        onset: 1e9,
        EA: 0,
        ED: 0,
        const_E6: true,
        E6i: 0.1,
        MMAX: 1e15
    },
   
   Impacts: {
        M_REF: 4e18,
        tau: 0.15e9,
        F0: 4.7e6,
        F1: 4.7e9,
    },
   
   AbioticFixation: {
        M_REF: 4e18,
        Fi_NOx: 4.0e10,
        Fi_NH3: 1.6e7,
        Ff_NOx: 2.6e6,
        Ff_NH3: 1.0e3,
        tau: 0.1e9,
        goe: 100e9
    },
   
   CometDelivery: {
        tau: 0.15e9,
        F0: 1.02e7,
        F1: 1.02e10,
    },
   
   FreundlichAdsorption: {
        VSed: 6.1e17,
        rhoSed: 1700,
        Kf: 1e-3
    },
   
   HydrothermalCirculation: {
        tau: 150e6, 
        F0: 1e-7,
        F1: 3e-7,
        F_p: 0.5,
    },
   
   Convection: {
        tau: 1e9, 
        F0: 1e-8,
        F1: 3e-8,
    },
   
   Subduction: {
        accretion: 0.05,
        tau: 100e6, 
        VCrust: 7.58e18
    },
   
   Volcanism: {
        F_arc: 0.5,
        F_MORB: 20,
        F_hotspot: 2, 
        density: 2800,
        scaling: 1e21
    },

    Accretion: {
        F0: 
    },
   
    atm_ox: 0.2,
    man_ox: 0.2,
    OutFolder: "output",
    Tmax: 4500e6,
    Output: 10e6,
    Timestep: 5e3,
    Debug: False
}
